export const MAX_ORGANISATION_SHOWN_IN_GIFTCARD = 5
export const MAX_ORGANISATION_LOGOS_SHOWN_IN_GIFTCARD = 6
export const MAX_CAUSE_POSTERS_SHOWN_IN_GIFTCARD = 2

export const GIFTCARD_MIN_SCHEDULE_DELAY = 3
