# This workflow will run deploy index.html to google cloud storage

name: Deploy to google cloud storage

on:
  push:
    branches: [feature-deploy]
  pull_request:
    branches: [feature-deploy]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
      - run: npx gulp
      - name: Cloud Storage Uploader
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          path: build/index.html
          destination: widget-react
