# This workflow will run the unit tests and upload the build artifact to google cloud storage

name: Deploy to google cloud storage

on:
  push:
    branches: [dev]

env:
  REACT_APP_API_URL: https://europe-west2-geeffektivt-se-dev.cloudfunctions.net/
  REACT_APP_USE_DEV_DATA: false

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      - name: Upload index.html to Google Cloud Storage bucket
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          path: build
          destination: geeffektivt-se-frontend-0e976eb
          parent: false
