# This workflow will run the unit tests and upload the build artifact to google cloud storage DEV

name: Deploy to google cloud storage DEV

on:
  push:
    branches: [dev]

env:
  REACT_APP_API_URL: https://europe-west2-geeffektivt-se-dev.cloudfunctions.net/
  REACT_APP_USE_DEV_DATA: false

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      - name: Validate directory not empty
        run: '[ "$(ls -A ./build/static/js && ls -A ./build/static/css)" ] && echo "Files exist - all good." || (echo "Directory is empty - aborting." && exit 1)'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_DEV }}'
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Upload build folder to Google Cloud Storage bucket
        run: 'gsutil -m rsync -d -r -j html,js,css,txt ./build gs://geeffektivt-se-frontend-0e976eb'
